# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/HookShare/New folder"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/HookShare/New folder"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/HookShare/New folder/CMakeFiles" "/home/HookShare/New folder/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/HookShare/New folder/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cpslCompiler

# Build rule for target.
cpslCompiler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpslCompiler
.PHONY : cpslCompiler

# fast build rule for target.
cpslCompiler/fast:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/build
.PHONY : cpslCompiler/fast

Asembler.o: Asembler.cpp.o

.PHONY : Asembler.o

# target to build an object file
Asembler.cpp.o:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/Asembler.cpp.o
.PHONY : Asembler.cpp.o

Asembler.i: Asembler.cpp.i

.PHONY : Asembler.i

# target to preprocess a source file
Asembler.cpp.i:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/Asembler.cpp.i
.PHONY : Asembler.cpp.i

Asembler.s: Asembler.cpp.s

.PHONY : Asembler.s

# target to generate assembly for a file
Asembler.cpp.s:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/Asembler.cpp.s
.PHONY : Asembler.cpp.s

Global.o: Global.cpp.o

.PHONY : Global.o

# target to build an object file
Global.cpp.o:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/Global.cpp.o
.PHONY : Global.cpp.o

Global.i: Global.cpp.i

.PHONY : Global.i

# target to preprocess a source file
Global.cpp.i:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/Global.cpp.i
.PHONY : Global.cpp.i

Global.s: Global.cpp.s

.PHONY : Global.s

# target to generate assembly for a file
Global.cpp.s:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/Global.cpp.s
.PHONY : Global.cpp.s

MiddleAsembler.o: MiddleAsembler.cpp.o

.PHONY : MiddleAsembler.o

# target to build an object file
MiddleAsembler.cpp.o:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/MiddleAsembler.cpp.o
.PHONY : MiddleAsembler.cpp.o

MiddleAsembler.i: MiddleAsembler.cpp.i

.PHONY : MiddleAsembler.i

# target to preprocess a source file
MiddleAsembler.cpp.i:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/MiddleAsembler.cpp.i
.PHONY : MiddleAsembler.cpp.i

MiddleAsembler.s: MiddleAsembler.cpp.s

.PHONY : MiddleAsembler.s

# target to generate assembly for a file
MiddleAsembler.cpp.s:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/MiddleAsembler.cpp.s
.PHONY : MiddleAsembler.cpp.s

Operations.o: Operations.cpp.o

.PHONY : Operations.o

# target to build an object file
Operations.cpp.o:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/Operations.cpp.o
.PHONY : Operations.cpp.o

Operations.i: Operations.cpp.i

.PHONY : Operations.i

# target to preprocess a source file
Operations.cpp.i:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/Operations.cpp.i
.PHONY : Operations.cpp.i

Operations.s: Operations.cpp.s

.PHONY : Operations.s

# target to generate assembly for a file
Operations.cpp.s:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/Operations.cpp.s
.PHONY : Operations.cpp.s

SymbolTable.o: SymbolTable.cpp.o

.PHONY : SymbolTable.o

# target to build an object file
SymbolTable.cpp.o:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/SymbolTable.cpp.o
.PHONY : SymbolTable.cpp.o

SymbolTable.i: SymbolTable.cpp.i

.PHONY : SymbolTable.i

# target to preprocess a source file
SymbolTable.cpp.i:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/SymbolTable.cpp.i
.PHONY : SymbolTable.cpp.i

SymbolTable.s: SymbolTable.cpp.s

.PHONY : SymbolTable.s

# target to generate assembly for a file
SymbolTable.cpp.s:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/SymbolTable.cpp.s
.PHONY : SymbolTable.cpp.s

Type.o: Type.cpp.o

.PHONY : Type.o

# target to build an object file
Type.cpp.o:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/Type.cpp.o
.PHONY : Type.cpp.o

Type.i: Type.cpp.i

.PHONY : Type.i

# target to preprocess a source file
Type.cpp.i:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/Type.cpp.i
.PHONY : Type.cpp.i

Type.s: Type.cpp.s

.PHONY : Type.s

# target to generate assembly for a file
Type.cpp.s:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/Type.cpp.s
.PHONY : Type.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/main.cpp.s
.PHONY : main.cpp.s

parser.o: parser.cpp.o

.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i

.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s

.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/parser.cpp.s
.PHONY : parser.cpp.s

scanner.o: scanner.cpp.o

.PHONY : scanner.o

# target to build an object file
scanner.cpp.o:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/scanner.cpp.o
.PHONY : scanner.cpp.o

scanner.i: scanner.cpp.i

.PHONY : scanner.i

# target to preprocess a source file
scanner.cpp.i:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/scanner.cpp.i
.PHONY : scanner.cpp.i

scanner.s: scanner.cpp.s

.PHONY : scanner.s

# target to generate assembly for a file
scanner.cpp.s:
	$(MAKE) -f CMakeFiles/cpslCompiler.dir/build.make CMakeFiles/cpslCompiler.dir/scanner.cpp.s
.PHONY : scanner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... cpslCompiler"
	@echo "... edit_cache"
	@echo "... Asembler.o"
	@echo "... Asembler.i"
	@echo "... Asembler.s"
	@echo "... Global.o"
	@echo "... Global.i"
	@echo "... Global.s"
	@echo "... MiddleAsembler.o"
	@echo "... MiddleAsembler.i"
	@echo "... MiddleAsembler.s"
	@echo "... Operations.o"
	@echo "... Operations.i"
	@echo "... Operations.s"
	@echo "... SymbolTable.o"
	@echo "... SymbolTable.i"
	@echo "... SymbolTable.s"
	@echo "... Type.o"
	@echo "... Type.i"
	@echo "... Type.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... scanner.o"
	@echo "... scanner.i"
	@echo "... scanner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

